### ISSUE TITLE
SetFieldOfView using patch_fog instead patch_fov

### ISSUE THREAD

**Issue by Marisa-Chan** [GregLando113/GWCA-Public#3]
Please correct it because it's may cause memory leak:

void GW::CameraMgr::SetFieldOfView(float fov) {
	if (patch_fog == nullptr) {

Must be 
void GW::CameraMgr::SetFieldOfView(float fov) {
	if (patch_fov == nullptr) {

**Comment by reduf** [comment]
Nice catch.

Would not memory leak, but rather crash.
